function [] = segLatVen_QSM(examPath, segfile_root)

if exist([segfile_root '/QSMseg_seg_0.nii.gz'],'file') ~= 2
    % extracted brain
    cmd = sprintf('3dcalc -a %s -b %s -expr a*b -prefix %s',...
        [examPath '/swan_qsm/HDBET_allQSM/Magni.nii.gz'],...
        [examPath '/swan_qsm/HDBET_allQSM/brain_mask_HD.nii.gz'],...
        [examPath '/swan_qsm/HDBET_allQSM/Magni_brain.nii.gz']);
    system(cmd);
    % tissue segmentation
    cmd = sprintf('fast -t 3 -g -o %s -v %s', ...
        [segfile_root '/QSMseg'], ...
        [examPath '/swan_qsm/HDBET_allQSM/Magni_brain.nii.gz']);
    system(cmd);
end

if exist([segfile_root '/QSMseg_latven.nii.gz'],'file') ~= 2
    % erosion of brain mask and crop the lower half
    cmd = sprintf('3dmask_tool -input %s -prefix %s -dilate_result -10', ...
        [examPath '/swan_qsm/HDBET_allQSM/brain_mask_HD.nii.gz'], ...
        [segfile_root '/brain_mask_erosion.nii.gz']);
    system(cmd);
    cmd = sprintf('3dcalc -a %s -expr ''step(70-k)'' -prefix %s', ...
        [segfile_root '/brain_mask_erosion.nii.gz'], ...
        [segfile_root '/zcrop.nii.gz']);
    system(cmd);
    % erosion of CSF mask and crop
    cmd = sprintf('3dmask_tool -input %s -prefix %s -dilate_result -1', ...
        [segfile_root '/QSMseg_seg_0.nii.gz'], ...
        [segfile_root '/QSMseg_csf_erosion.nii.gz']);
    system(cmd);
    cmd = sprintf('3dcalc -a %s -b %s -c %s -expr a*b*c -prefix %s', ...
        [segfile_root '/QSMseg_csf_erosion.nii.gz'], ...
        [segfile_root '/brain_mask_erosion.nii.gz'], ...
        [segfile_root '/zcrop.nii.gz'], ...
        [segfile_root '/QSMseg_csf_mask.nii.gz']);
    system(cmd);
    % calculate cluster and threshold cluster size for final mask
    cmd = sprintf('cluster -i %s -t 1 --osize=%s', ...
        [segfile_root '/QSMseg_csf_mask.nii.gz'], ...
        [segfile_root '/QSMseg_csf_cluster.nii.gz']);
    system(cmd);
    cmd = sprintf('3dcalc -a %s -expr ''step(a-200)'' -prefix %s', ...
        [segfile_root '/QSMseg_csf_cluster.nii.gz'], ...
        [segfile_root '/QSMseg_latven.nii.gz']);
    system(cmd);
end